### ISSUE TITLE
Nothing happens, when i start example_ListFixtureGroup and example_ListColorGel

### ISSUE THREAD

**Issue by Montezuma-69** [imhofroger/GMA3_LUA#3]
Hi Roger,

ive tried to start your scripts, but nothing happens, when i start example_ListFixtureGroup or example_ListColorGel. No choice List appears. 

MA3 1.0.0.3 onPC

Any ideas or proposals?

Servus aus München

**Comment by imhofroger** [comment]
Hi
After a clean install of GMA3 i had the same problem.
Now the Bugfixed Version are Online.
thx
